# Site Settings
lang: en
title: Chisuma Foundation
tagline: Chisuma Foundation
email: chisumafoundation@gmail.com
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chisumafoundation.github.io" # the base hostname & protocol for your site, e.g. http://example.co
permalink: pretty
#favicon: /path/to/favicon.png
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  # shortname: chisumafoundation

facebook_username: chisumafoundationtrust
twitter_username: chisumafdn
github_username:  chisumafoundation # replace with your_github_username or comment to remove link from footer

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: "assets/img"
      type: "posts"
    values:
      author: "Chisuma Foundation"
      layout: post
      image: true
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
